// src/components/ForecastTable.jsx
import React, { useState } from 'react';
import { SIZES, FIRMNESSES, FIRMNESS_LABELS, LEAD_TIME_MONTHS } from '../lib/constants';
import { calculateProjection } from '../lib/algorithms';

// ForecastTable - Shows 12-month stock projections

function getCellColor(value) {
  if (value < 0) return '#ef4444'; // Red - stockout
  if (value < 20) return '#f97316'; // Orange - critical
  if (value < 50) return '#eab308'; // Yellow - low
  return '#22c55e'; // Green - healthy
}

const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export default function ForecastTable({ inventory, order, usageRates = null }) {
  const [isExpanded, setIsExpanded] = useState(true); // Expanded by default

  const today = new Date();
  const startMonth = today.getMonth();

  const getMonthLabel = (offset) => {
    if (offset === 0) return 'Now';
    return MONTH_NAMES[(startMonth + offset) % 12];
  };

  const projections = calculateProjection(inventory, order, 12, usageRates);

  return (
    <div style={styles.container}>
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        style={styles.header}
      >
        <span style={styles.headerTitle}>
          {isExpanded ? '▼' : '▶'} 12-Month Forecast
        </span>
        <span style={styles.headerHint}>Container arrives month 3</span>
      </button>

      {isExpanded && (
        <div style={styles.content}>
          <div style={styles.tableWrapper}>
            <table style={styles.table}>
              <thead>
                <tr>
                  <th style={{ ...styles.th, position: 'sticky', left: 0, background: '#0a0a0a', zIndex: 2 }}>
                    SKU
                  </th>
                  {projections.map((_, idx) => (
                    <th
                      key={idx}
                      style={{
                        ...styles.th,
                        ...(idx === LEAD_TIME_MONTHS ? styles.arrivalHeader : {})
                      }}
                    >
                      {idx === LEAD_TIME_MONTHS ? '📦 ' : ''}
                      {getMonthLabel(idx)}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {SIZES.map(size => (
                  <React.Fragment key={size}>
                    {/* Size header row */}
                    <tr>
                      <td colSpan={projections.length + 1} style={styles.sizeHeader}>
                        {size}
                      </td>
                    </tr>
                    {/* Firmness rows */}
                    {FIRMNESSES.map(firmness => {
                      const key = `${size}_${firmness}`;
                      return (
                        <tr key={key}>
                          <td style={{ ...styles.tdLabel, position: 'sticky', left: 0, background: '#0a0a0a', zIndex: 1 }}>
                            {FIRMNESS_LABELS[firmness]}
                          </td>
                          {projections.map((monthData, idx) => {
                            const value = monthData[key];
                            const isArrival = idx === LEAD_TIME_MONTHS;
                            return (
                              <td
                                key={idx}
                                style={{
                                  ...styles.tdValue,
                                  color: getCellColor(value),
                                  ...(isArrival ? styles.arrivalCell : {})
                                }}
                              >
                                {value < 0 ? value : value}
                              </td>
                            );
                          })}
                        </tr>
                      );
                    })}
                  </React.Fragment>
                ))}
              </tbody>
            </table>
          </div>

          <div style={styles.legend}>
            <span style={styles.legendItem}>
              <span style={{ ...styles.legendDot, background: '#22c55e' }}></span>
              Healthy (50+)
            </span>
            <span style={styles.legendItem}>
              <span style={{ ...styles.legendDot, background: '#eab308' }}></span>
              Low (20-49)
            </span>
            <span style={styles.legendItem}>
              <span style={{ ...styles.legendDot, background: '#f97316' }}></span>
              Critical (&lt;20)
            </span>
            <span style={styles.legendItem}>
              <span style={{ ...styles.legendDot, background: '#ef4444' }}></span>
              Stockout (&lt;0)
            </span>
          </div>
        </div>
      )}
    </div>
  );
}

const styles = {
  container: {
    background: '#0a0a0a',
    border: '1px solid #27272a',
    borderRadius: '12px',
    overflow: 'hidden',
    marginBottom: '16px'
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    padding: '16px 20px',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: '#fafafa'
  },
  headerTitle: {
    fontSize: '15px',
    fontWeight: '600'
  },
  headerHint: {
    fontSize: '12px',
    color: '#71717a'
  },
  content: {
    padding: '0 20px 20px'
  },
  tableWrapper: {
    overflowX: 'auto',
    border: '1px solid #27272a',
    borderRadius: '8px'
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '13px',
    fontFamily: 'monospace'
  },
  th: {
    padding: '10px 8px',
    textAlign: 'center',
    color: '#a1a1aa',
    fontWeight: '600',
    borderBottom: '1px solid #27272a',
    whiteSpace: 'nowrap',
    minWidth: '50px'
  },
  arrivalHeader: {
    background: 'rgba(59, 130, 246, 0.15)',
    color: '#60a5fa'
  },
  sizeHeader: {
    padding: '10px 12px',
    fontWeight: '700',
    fontSize: '13px',
    color: '#fafafa',
    background: '#18181b',
    borderBottom: '1px solid #27272a'
  },
  tdLabel: {
    padding: '8px 12px',
    color: '#a1a1aa',
    borderBottom: '1px solid #27272a',
    fontSize: '12px',
    whiteSpace: 'nowrap'
  },
  tdValue: {
    padding: '8px',
    textAlign: 'center',
    borderBottom: '1px solid #27272a',
    fontWeight: '500'
  },
  arrivalCell: {
    background: 'rgba(59, 130, 246, 0.1)'
  },
  legend: {
    display: 'flex',
    gap: '16px',
    flexWrap: 'wrap',
    marginTop: '16px',
    fontSize: '12px',
    color: '#a1a1aa'
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px'
  },
  legendDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%'
  }
};

// components/ForecastTable.vue
<script setup>
import { SIZES, FIRMNESSES, FIRMNESS_LABELS, LEAD_TIME_MONTHS } from '~/utils/constants'
import { calculateProjection } from '~/utils/algorithms'

const store = useOrderStore()
const { inventory, order, usageRates } = storeToRefs(store)

const isExpanded = ref(true)

const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

const projections = computed(() => {
  return calculateProjection(inventory.value, order.value, 12, usageRates.value)
})

const startMonth = computed(() => new Date().getMonth())

const getMonthLabel = (offset) => {
  if (offset === 0) return 'Now'
  return MONTH_NAMES[(startMonth.value + offset) % 12]
}

const getCellColor = (value) => {
  if (value < 0) return 'text-status-critical' // Red - stockout
  if (value < 20) return 'text-status-warning' // Orange - critical
  if (value < 50) return 'text-status-caution' // Yellow - low
  return 'text-status-healthy' // Green - healthy
}
</script>

<template>
  <div class="bg-surface-darker border border-surface-border rounded-xl overflow-hidden mb-4">
    <button
      @click="isExpanded = !isExpanded"
      class="flex justify-between items-center w-full px-5 py-4 bg-transparent border-none cursor-pointer text-zinc-50"
    >
      <span class="text-[15px] font-semibold">
        <span class="mr-2">{{ isExpanded ? '▼' : '▶' }}</span>
        12-Month Forecast
      </span>
      <span class="text-xs text-zinc-500">Container arrives month 3</span>
    </button>

    <div v-if="isExpanded" class="px-5 pb-5">
      <div class="overflow-x-auto border border-surface-border rounded-lg">
        <table class="w-full border-collapse text-sm font-mono">
          <thead>
            <tr>
              <th class="px-3 py-2.5 text-center text-zinc-400 font-semibold border-b border-surface-border whitespace-nowrap min-w-[50px] sticky left-0 bg-surface-darker z-[2]">
                SKU
              </th>
              <th
                v-for="(_, idx) in projections"
                :key="idx"
                class="px-2 py-2.5 text-center text-zinc-400 font-semibold border-b border-surface-border whitespace-nowrap min-w-[50px]"
                :class="{ 'bg-blue-500/15 text-blue-400': idx === LEAD_TIME_MONTHS }"
              >
                <span v-if="idx === LEAD_TIME_MONTHS">
                  <Icon name="mdi:package-variant" class="w-4 h-4 mr-1 inline" />
                </span>
                {{ getMonthLabel(idx) }}
              </th>
            </tr>
          </thead>
          <tbody>
            <template v-for="size in SIZES" :key="size">
              <!-- Size header row -->
              <tr>
                <td :colspan="projections.length + 1" class="px-3 py-2.5 font-bold text-sm text-zinc-50 bg-surface border-b border-surface-border">
                  {{ size }}
                </td>
              </tr>
              <!-- Firmness rows -->
              <tr v-for="firmness in FIRMNESSES" :key="`${size}_${firmness}`">
                <td class="px-3 py-2 text-zinc-400 border-b border-surface-border text-xs whitespace-nowrap sticky left-0 bg-surface-darker z-[1]">
                  {{ FIRMNESS_LABELS[firmness] }}
                </td>
                <td
                  v-for="(monthData, idx) in projections"
                  :key="idx"
                  class="px-2 py-2 text-center border-b border-surface-border font-medium"
                  :class="[
                    getCellColor(monthData[`${size}_${firmness}`]),
                    { 'bg-blue-500/10': idx === LEAD_TIME_MONTHS }
                  ]"
                >
                  {{ monthData[`${size}_${firmness}`] }}
                </td>
              </tr>
            </template>
          </tbody>
        </table>
      </div>

      <div class="flex gap-4 flex-wrap mt-4 text-xs text-zinc-400">
        <span class="flex items-center gap-1.5">
          <span class="w-2.5 h-2.5 rounded-full bg-status-healthy"></span>
          Healthy (50+)
        </span>
        <span class="flex items-center gap-1.5">
          <span class="w-2.5 h-2.5 rounded-full bg-status-caution"></span>
          Low (20-49)
        </span>
        <span class="flex items-center gap-1.5">
          <span class="w-2.5 h-2.5 rounded-full bg-status-warning"></span>
          Critical (&lt;20)
        </span>
        <span class="flex items-center gap-1.5">
          <span class="w-2.5 h-2.5 rounded-full bg-status-critical"></span>
          Stockout (&lt;0)
        </span>
      </div>
    </div>
  </div>
</template>
