// src/components/InventoryMix.jsx
import React from 'react';
import { SIZES, FIRMNESSES, FIRMNESS_LABELS, CRITICAL_THRESHOLD_MONTHS } from '../lib/constants';
import { calculateSKUCoverage } from '../lib/algorithms';

function getStatusInfo(coverage) {
  if (coverage < 2) return { color: '#ef4444', label: 'CRITICAL', icon: '🔴' };
  if (coverage < 3) return { color: '#f97316', label: 'LOW', icon: '⚠️' };
  if (coverage < CRITICAL_THRESHOLD_MONTHS) return { color: '#eab308', label: 'WARNING', icon: '⚠️' };
  if (coverage > 8) return { color: '#3b82f6', label: 'OVER', icon: '▲' };
  return { color: '#22c55e', label: 'OK', icon: '✓' };
}

export default function InventoryMix({ inventory, usageRates }) {
  // Calculate coverage for all SKUs
  const skuData = [];
  let totalStock = 0;

  for (const size of SIZES) {
    for (const firmness of FIRMNESSES) {
      const stock = inventory[firmness]?.[size] ?? 0;
      const coverage = calculateSKUCoverage(stock, size, firmness, usageRates);
      const monthlyUsage = usageRates?.SKU_MONTHLY_USAGE?.[size]?.[firmness] ?? 0;

      skuData.push({
        size,
        firmness,
        stock,
        coverage,
        monthlyUsage,
        key: `${size}_${firmness}`
      });
      totalStock += stock;
    }
  }

  // Sort by coverage (lowest first - most urgent)
  const sortedData = [...skuData].sort((a, b) => a.coverage - b.coverage);

  // Find issues
  const critical = sortedData.filter(s => s.coverage < CRITICAL_THRESHOLD_MONTHS);
  const overstocked = sortedData.filter(s => s.coverage > 8);

  // Max coverage for bar scaling (cap at 12 months for display)
  const maxCoverage = 12;

  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <h3 style={styles.title}>Stock Runway</h3>
        <div style={styles.targetLine}>
          Target: {CRITICAL_THRESHOLD_MONTHS} months
        </div>
      </div>

      <div style={styles.barList}>
        {skuData.map(({ size, firmness, stock, coverage, monthlyUsage, key }) => {
          const status = getStatusInfo(coverage);
          const barWidth = Math.min(100, (coverage / maxCoverage) * 100);
          const targetPosition = (CRITICAL_THRESHOLD_MONTHS / maxCoverage) * 100;

          return (
            <div key={key} style={styles.row}>
              <div style={styles.label}>
                <span style={styles.sizeName}>{size}</span>
                <span style={styles.firmnessName}>{FIRMNESS_LABELS[firmness]}</span>
              </div>

              <div style={styles.barContainer}>
                <div
                  style={{
                    ...styles.targetMarker,
                    left: `${targetPosition}%`
                  }}
                />
                <div
                  style={{
                    ...styles.bar,
                    width: `${barWidth}%`,
                    background: status.color
                  }}
                />
              </div>

              <div style={styles.stats}>
                <span style={{ ...styles.coverage, color: status.color }}>
                  {coverage > 99 ? '99+' : coverage.toFixed(1)} mo
                </span>
                <span style={{ ...styles.status, color: status.color }}>
                  {status.icon}
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Insights */}
      {(critical.length > 0 || overstocked.length > 0) && (
        <div style={styles.insights}>
          {critical.length > 0 && (
            <div style={styles.insightRow}>
              <span style={styles.insightIcon}>🔴</span>
              <span style={styles.insightText}>
                <strong>Will run out before container:</strong>{' '}
                {critical.map(s => `${s.size} ${s.firmness} (${s.coverage.toFixed(1)}mo)`).join(', ')}
              </span>
            </div>
          )}
          {overstocked.length > 0 && (
            <div style={styles.insightRow}>
              <span style={styles.insightIcon}>▲</span>
              <span style={styles.insightText}>
                <strong>Overstocked:</strong>{' '}
                {overstocked.map(s => `${s.size} ${s.firmness} (${s.coverage.toFixed(1)}mo)`).join(', ')}
                {overstocked.some(s => s.firmness === 'firm') &&
                  ' — Firm sells slowly (5% of demand)'}
              </span>
            </div>
          )}
        </div>
      )}

      <div style={styles.footer}>
        <span>Total: {totalStock} units in stock</span>
        <span style={styles.footerNote}>Lead time: 3 months | Buffer: 1 month</span>
      </div>

      {/* Demand Breakdown Card */}
      <DemandBreakdown usageRates={usageRates} />
    </div>
  );
}

function DemandBreakdown({ usageRates }) {
  const totalMonthly = usageRates?.TOTAL_MONTHLY_SALES ?? 0;
  const totalWeekly = totalMonthly / 4.33; // Convert monthly to weekly

  // Build table data for all variations
  const variations = [];
  for (const size of SIZES) {
    for (const firmness of FIRMNESSES) {
      const monthlyUnits = usageRates?.SKU_MONTHLY_USAGE?.[size]?.[firmness] ?? 0;
      const weeklyUnits = monthlyUnits / 4.33;
      const pct = totalMonthly > 0 ? (monthlyUnits / totalMonthly) * 100 : 0;
      variations.push({
        size,
        firmness,
        weeklyUnits,
        pct
      });
    }
  }

  return (
    <div style={demandStyles.container}>
      <div style={demandStyles.header}>
        <h3 style={demandStyles.title}>Demand Breakdown</h3>
        <div style={demandStyles.badge}>
          {totalWeekly.toFixed(1)}/wk total
        </div>
      </div>

      {/* Table */}
      <table style={demandStyles.table}>
        <thead>
          <tr>
            <th style={demandStyles.th}>Variation</th>
            <th style={demandStyles.thRight}>Units/Wk</th>
            <th style={demandStyles.thRight}>%</th>
          </tr>
        </thead>
        <tbody>
          {variations.map(({ size, firmness, weeklyUnits, pct }) => (
            <tr key={`${size}_${firmness}`} style={demandStyles.tr}>
              <td style={demandStyles.td}>
                <span style={demandStyles.sizeBadge}>{size}</span>
                <span style={demandStyles.firmnessBadge}>{firmness.charAt(0).toUpperCase() + firmness.slice(1)}</span>
              </td>
              <td style={demandStyles.tdRight}>
                {weeklyUnits.toFixed(1)}
              </td>
              <td style={demandStyles.tdRight}>
                {pct.toFixed(0)}%
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

const demandStyles = {
  container: {
    marginTop: '24px',
    padding: '16px',
    background: '#18181b',
    border: '1px solid #27272a',
    borderRadius: '12px',
    maxWidth: '320px'
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px'
  },
  title: {
    margin: 0,
    fontSize: '13px',
    fontWeight: '600',
    color: '#a1a1aa',
    textTransform: 'uppercase',
    letterSpacing: '0.5px'
  },
  badge: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#22c55e',
    padding: '3px 8px',
    background: 'rgba(34, 197, 94, 0.1)',
    borderRadius: '4px'
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse'
  },
  th: {
    padding: '6px 8px',
    fontSize: '10px',
    fontWeight: '600',
    color: '#71717a',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    borderBottom: '1px solid #27272a',
    textAlign: 'left'
  },
  thRight: {
    padding: '6px 8px',
    fontSize: '10px',
    fontWeight: '600',
    color: '#71717a',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    borderBottom: '1px solid #27272a',
    textAlign: 'right',
    width: '70px'
  },
  tr: {
    borderBottom: '1px solid #27272a'
  },
  td: {
    padding: '8px',
    fontSize: '13px',
    color: '#fafafa'
  },
  tdRight: {
    padding: '8px',
    fontSize: '13px',
    color: '#fafafa',
    textAlign: 'right',
    fontFamily: 'monospace'
  },
  sizeBadge: {
    display: 'inline-block',
    padding: '2px 6px',
    fontSize: '10px',
    fontWeight: '600',
    color: '#fafafa',
    background: '#3b82f6',
    borderRadius: '3px',
    marginRight: '6px'
  },
  firmnessBadge: {
    fontSize: '12px',
    color: '#a1a1aa'
  }
};

const styles = {
  container: {
    background: '#0a0a0a',
    border: '1px solid #27272a',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '24px'
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px'
  },
  title: {
    margin: 0,
    fontSize: '16px',
    fontWeight: '600',
    color: '#fafafa'
  },
  targetLine: {
    fontSize: '12px',
    color: '#71717a',
    padding: '4px 8px',
    background: '#18181b',
    borderRadius: '4px'
  },
  barList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px'
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px'
  },
  label: {
    width: '140px',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '2px'
  },
  sizeName: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#fafafa'
  },
  firmnessName: {
    fontSize: '11px',
    color: '#71717a'
  },
  barContainer: {
    flex: 1,
    height: '20px',
    background: '#18181b',
    borderRadius: '4px',
    position: 'relative',
    overflow: 'hidden'
  },
  bar: {
    height: '100%',
    borderRadius: '4px',
    transition: 'width 0.3s ease'
  },
  targetMarker: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '2px',
    background: '#fafafa',
    opacity: 0.3,
    zIndex: 1
  },
  stats: {
    width: '80px',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '8px'
  },
  coverage: {
    fontSize: '13px',
    fontWeight: '600',
    fontFamily: 'monospace'
  },
  status: {
    fontSize: '12px'
  },
  insights: {
    marginTop: '16px',
    padding: '12px',
    background: '#18181b',
    borderRadius: '8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px'
  },
  insightRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px'
  },
  insightIcon: {
    fontSize: '12px',
    flexShrink: 0
  },
  insightText: {
    fontSize: '12px',
    color: '#a1a1aa',
    lineHeight: '1.4'
  },
  footer: {
    marginTop: '16px',
    paddingTop: '12px',
    borderTop: '1px solid #27272a',
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '12px',
    color: '#71717a'
  },
  footerNote: {
    color: '#52525b'
  }
};

// components/InventoryMix.vue
<script setup>
import { SIZES, FIRMNESSES, FIRMNESS_LABELS, CRITICAL_THRESHOLD_MONTHS } from '~/utils/constants'
import { calculateSKUCoverage } from '~/utils/algorithms'

const store = useOrderStore()
const { inventory, usageRates } = storeToRefs(store)

const getStatusInfo = (coverage) => {
  if (coverage < 2) return { color: 'bg-status-critical', textColor: 'text-status-critical', label: 'CRITICAL', iconName: 'mdi:alert-circle' }
  if (coverage < 3) return { color: 'bg-status-warning', textColor: 'text-status-warning', label: 'LOW', iconName: 'mdi:alert' }
  if (coverage < CRITICAL_THRESHOLD_MONTHS) return { color: 'bg-status-caution', textColor: 'text-status-caution', label: 'WARNING', iconName: 'mdi:alert' }
  if (coverage > 8) return { color: 'bg-blue-500', textColor: 'text-blue-500', label: 'OVER', iconName: 'mdi:arrow-up' }
  return { color: 'bg-status-healthy', textColor: 'text-status-healthy', label: 'OK', iconName: 'mdi:check-circle' }
}

const skuData = computed(() => {
  const data = []
  let totalStock = 0

  for (const size of SIZES) {
    for (const firmness of FIRMNESSES) {
      const stock = inventory.value[firmness]?.[size] ?? 0
      const coverage = calculateSKUCoverage(stock, size, firmness, usageRates.value)
      const monthlyUsage = usageRates.value?.SKU_MONTHLY_USAGE?.[size]?.[firmness] ?? 0

      data.push({
        size,
        firmness,
        stock,
        coverage,
        monthlyUsage,
        key: `${size}_${firmness}`,
        status: getStatusInfo(coverage)
      })
      totalStock += stock
    }
  }

  return { items: data, totalStock }
})

const sortedData = computed(() => {
  return [...skuData.value.items].sort((a, b) => a.coverage - b.coverage)
})

const criticalSKUs = computed(() => {
  return sortedData.value.filter(s => s.coverage < CRITICAL_THRESHOLD_MONTHS)
})

const overstockedSKUs = computed(() => {
  return sortedData.value.filter(s => s.coverage > 8)
})

const maxCoverage = 12
const targetPosition = (CRITICAL_THRESHOLD_MONTHS / maxCoverage) * 100
</script>

<template>
  <div class="bg-surface-darker border border-surface-border rounded-xl p-5 mb-6">
    <div class="flex justify-between items-center mb-4">
      <h3 class="text-base font-semibold text-zinc-50">Stock Runway</h3>
      <div class="text-xs text-zinc-500 px-2 py-1 bg-surface rounded">
        Target: {{ CRITICAL_THRESHOLD_MONTHS }} months
      </div>
    </div>

    <div class="flex flex-col gap-2">
      <div
        v-for="item in skuData.items"
        :key="item.key"
        class="flex items-center gap-3"
      >
        <div class="w-[140px] flex-shrink-0 flex flex-col gap-0.5">
          <span class="text-sm font-semibold text-zinc-50">{{ item.size }}</span>
          <span class="text-[11px] text-zinc-500">{{ FIRMNESS_LABELS[item.firmness] }}</span>
        </div>

        <div class="flex-1 h-5 bg-surface rounded relative overflow-hidden">
          <div
            class="absolute top-0 bottom-0 w-0.5 bg-white/30 z-[1]"
            :style="{ left: targetPosition + '%' }"
          ></div>
          <div
            class="h-full rounded transition-all duration-300"
            :class="item.status.color"
            :style="{ width: Math.min(100, (item.coverage / maxCoverage) * 100) + '%' }"
          ></div>
        </div>

        <div class="w-20 flex-shrink-0 flex items-center justify-end gap-2">
          <span class="text-sm font-semibold font-mono" :class="item.status.textColor">
            {{ item.coverage > 99 ? '99+' : item.coverage.toFixed(1) }} mo
          </span>
          <Icon :name="item.status.iconName" class="w-4 h-4" :class="item.status.textColor" />
        </div>
      </div>
    </div>

    <!-- Insights -->
    <div v-if="criticalSKUs.length > 0 || overstockedSKUs.length > 0" class="mt-4 p-3 bg-surface rounded-lg flex flex-col gap-2">
      <div v-if="criticalSKUs.length > 0" class="flex items-start gap-2">
        <Icon name="mdi:alert-circle" class="w-4 h-4 text-status-critical flex-shrink-0 mt-0.5" />
        <span class="text-xs text-zinc-400 leading-relaxed">
          <strong class="text-zinc-300">Will run out before container:</strong>
          {{ criticalSKUs.map(s => `${s.size} ${s.firmness} (${s.coverage.toFixed(1)}mo)`).join(', ') }}
        </span>
      </div>
      <div v-if="overstockedSKUs.length > 0" class="flex items-start gap-2">
        <Icon name="mdi:arrow-up" class="w-4 h-4 text-blue-500 flex-shrink-0 mt-0.5" />
        <span class="text-xs text-zinc-400 leading-relaxed">
          <strong class="text-zinc-300">Overstocked:</strong>
          {{ overstockedSKUs.map(s => `${s.size} ${s.firmness} (${s.coverage.toFixed(1)}mo)`).join(', ') }}
          <span v-if="overstockedSKUs.some(s => s.firmness === 'firm')"> — Firm sells slowly (5% of demand)</span>
        </span>
      </div>
    </div>

    <div class="mt-4 pt-3 border-t border-surface-border flex justify-between text-xs text-zinc-500">
      <span>Total: {{ skuData.totalStock }} units in stock</span>
      <span class="text-zinc-600">Lead time: 3 months | Buffer: 1 month</span>
    </div>

    <!-- Demand Breakdown -->
    <DemandBreakdown />
  </div>
</template>
